### ISSUE TITLE
the location to run the main file

### ISSUE THREAD

**Issue by junxu-ai** [amjadraza/pandasai-app#1]
instead of "streamlit run main.py "

you might run 

streamlit run pandasai_app\main.py    # windows
streamlit run pandasai_app/main.py    # linux

Meanwhile, could you create this app in a conversional way? Thanks.

**Comment by amjadraza** [comment]
Yes, you are right. we can run form the root folder. While runner app in `docker` I used the above commands. 

This is WIP, we have to add other features. Stay Tuned.
