### ISSUE TITLE
Show Details About Python Code generated option chosed?

### ISSUE THREAD

**Issue by georgeqin96** [amjadraza/pandasai-app#2]
but I didn't see the python code, where is it?

**Comment by amjadraza** [comment]
What do you mean? Which Python Code?

**Comment by georgeqin96** [comment]
<img width="546" alt="image" src="https://github.com/amjadraza/pandasai-app/assets/134306905/c7440ba6-fc07-4550-9ac6-c7f9a4397aa6">  this option?
