### ISSUE TITLE
Numpy version too new ?

### ISSUE THREAD

**Issue by JonRickSanchez** [amjadraza/pandasai-app#3]
When trying to run according to instructions I get the below error message:

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

From my initial investigation this apparently seems to be problem with new version of numpy (2.1.2) at the time when I run it.

**Comment by amjadraza** [comment]
You are thinking in the right direction, it could be due to the dependency issues. The numpy release of 2.x happened after this repo was posted.  Let me check and push the changes with upgraded numpy, pandas and pandasai releases.

**Comment by amjadraza** [comment]
I have fixed it. please try again. Let me know if issue still persist.

**Comment by JonRickSanchez** [comment]
Hi Raza, Thank you for amazingly quick fix. That is working now :)
