### ISSUE TITLE
Support for feather files ?

### ISSUE THREAD

**Issue by JonRickSanchez** [amjadraza/pandasai-app#4]
Is it possible to add support for feather files, should be quite a simple change ?

I managed to make it work by changing 

file_formats = {
    "csv": pd.read_csv,
    "xls": pd.read_excel,
    "xlsx": pd.read_excel,
    "xlsm": pd.read_excel,
    "xlsb": pd.read_excel
}

to

file_formats = {
    "csv": pd.read_csv,
    "xls": pd.read_excel,
    "xlsx": pd.read_excel,
    "xlsm": pd.read_excel,
    "xlsb": pd.read_excel,
    "feather": pd.read_feather
}

**Comment by amjadraza** [comment]
added. It was a quick fix.
